name: myanmar_calendar_wear
description: Myanmar Calendar for Wear OS app
version: 1.0.0+34100 # [targetSdk][xxx][yy][zz]
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.0.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.3
  intl: ^0.20.2
  myanmar_calendar_dart: ^1.1.0
  wear_plus: ^1.2.4
  # wearable_rotary: ^2.0.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
